# Generated by Django 4.1.4 on 2022-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('username', models.CharField(max_length=40, verbose_name='Никнейм')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('location', models.CharField(blank=True, choices=[('MSC', 'Moscow'), ('SPB', 'Saint-Petersburg'), ('KZN', 'Kazan')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPartner',
            fields=[
                ('username', models.CharField(max_length=40, verbose_name='Никнейм')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('location', models.CharField(choices=[('MSC', 'Moscow'), ('SPB', 'Saint-Petersburg'), ('KZN', 'Kazan')], default='MSC', max_length=255)),
                ('service_type', models.CharField(choices=[('photo', 'Photographer'), ('DJ', 'Dj'), ('Food', 'Food'), ('Place', 'Place')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
