# Generated by Django 4.1.4 on 2023-01-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Moscow', max_length=60)),
                ('photo', models.ImageField(blank=True, upload_to='photo/locations/%Y/%m/%d', verbose_name='Фото')),
                ('description', models.CharField(default='Город не описан', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.locations'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.locations'),
        ),
    ]
