# Generated by Django 4.1.4 on 2023-01-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_locations_alter_baseevent_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
