# Generated by Django 4.1.4 on 2023-01-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_locations_options_alter_locations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo/homepage/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
    ]
