# Generated by Django 4.1.4 on 2022-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_userpartner_options_remove_userclient_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='django_user_id',
            field=models.IntegerField(default=1),
        ),
    ]
