# Generated by Django 4.1.4 on 2022-12-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userclient_django_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclient',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userclient',
            old_name='surname',
            new_name='last_name',
        ),
    ]
