# Generated by Django 4.1.4 on 2022-12-12 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_baseevent_eventvendors_baseevent_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='planning_day',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 13), verbose_name='Планируемое день события'),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='planning_time',
            field=models.TimeField(blank=True, verbose_name='Планируемое время события'),
        ),
    ]
