# Generated by Django 4.1.4 on 2022-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_baseevent_options_alter_eventvendors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpartner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userpartner',
            name='location',
            field=models.CharField(choices=[('MSC', 'Moscow'), ('SPB', 'Saint-Petersburg'), ('KZN', 'Kazan')], default='MSC', max_length=255, verbose_name='Город'),
        ),
    ]
